### ISSUE TITLE
编译windows x64 zbar

### ISSUE THREAD

**Issue by SuperChrisliu** [bertsir/zBarLibary#1]
兄弟，找了好多个项目一看你这个有x64的，惊喜的一笔，于是clone，放到我的项目里，运行了发现你的x64是linux平台的*.so，，，，，

我找到了 windows上的可以编译的[X64ZBAR](https://github.com/dani4/ZBarWin64)项目，测试vs2017确实能编译，不过这个编译好的是没有用jni包装的，也就是不能用java调。

我看到java wrapper 目录下有Makefile.am，但是研究了一下没有编译过，，

不知道兄台会不会编译windows的x64 jni包装的zbar库啊，可否指导一下

**Comment by bertsir** [comment]
因为我用的Android Studio 默认编译的是安卓用的linux的 .so  里面包含了包名等信息，有一个思路  在windows下用cmake手动编译一下试试

**Comment by SuperChrisliu** [comment]
放弃zbar了，现在使用opencv对图片进行预处理，再使用zxing解码，发现效果非常好，，
