### ISSUE TITLE
这个不能把你的so和代码拿出来直接用，包名不行，jni方法使用不了，能全部开源吗？

### ISSUE THREAD

**Issue by CayaQi** [bertsir/zBarLibary#10]
如题

**Comment by CayaQi** [comment]
请问 我在gradle里面发现这个，我是不是需要修改这些东西才能用so，怎么修改呢？

bintray {
    user = properties.getProperty("bintray.user")
    key = properties.getProperty("bintray.apikey")
    configurations = ['archives']
    pkg {
        repo = "zbar"  //发布到Bintray的那个仓库里，默认账户有四个库，我们这里上传到maven库
        name = "zbarLibary"  //需更改，这个名字就是你在Bintray上创建Package的名字，这里会查询，如果此包不存在就会创建一个。
        websiteUrl = siteUrl
        vcsUrl = gitUrl
        licenses = ["Apache-2.0"]
        publish = true
    }
}
//先执行   chmod a+x ./gradlew   ./gradlew install ，然后执行 ./gradlew bintrayUpload

**Comment by CayaQi** [comment]
错误 : No implementation found for void *.*.*.zbar.Qr.Symbol.init()

**Comment by bertsir** [comment]
@CayaQi 你是需要把代码放到你的项目中而不是以库的方式导入么

**Comment by CayaQi** [comment]
@bertsir 是的，我们可能也得弄些别的码。所以都得研究一下。想以你的代码为基础。

**Comment by bertsir** [comment]
@CayaQi 好了，提交了jni.zip

**Comment by CayaQi** [comment]
@bertsir 感谢 一会回家开始研究
