### ISSUE TITLE
大佬，你好。你的扫描库非常快，我想接入。但是貌似不支持Android x，能否支持下

### ISSUE THREAD

**Issue by strivecheng** [bertsir/zBarLibary#103]
能否支持下Android x，后面Android x已经是主流。as已经强制新建项目为Android x了

**Comment by bertsir** [comment]
@strivecheng 我刚尝试了一下引入使用好像都没问题，你那遇到什么问题了么

**Comment by strivecheng** [comment]
> @strivecheng 我刚尝试了一下引入使用好像都没问题，你那遇到什么问题了么

大佬，能否加个微信聊？ 我的微信号xcc2734

**Comment by strivecheng** [comment]
More than one file was found with OS independent path 'lib/mips/libiconv.so'

我的两个项目都报这个，一个是Android x，一个不是
