### ISSUE TITLE
摄像头权限被拒绝

### ISSUE THREAD

**Issue by afunnyrainman** [bertsir/zBarLibary#12]
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
 Fail to connect to camera service
输入e这些错误

**Comment by bertsir** [comment]
@afunnyrainman targetSdkVersion在22以上的自己处理一下权限请求试试，还有，是什么机型

**Comment by afunnyrainman** [comment]
魅族手机 pro6 s     可以了，申请一下权限就好了。原因是我自己开发APP的时候魅族手机不处理权限请求的时候系统会自动帮我申请，我用别的手机测试的时候才会去写申请权限。总之就是疏忽了，多谢大佬帮助。
