### ISSUE TITLE
关于安卓6.0以下的64位手机

### ISSUE THREAD

**Issue by Xu-YongFeng** [bertsir/zBarLibary#13]
6.0以下的手机貌似不需要提示开启相机权限，我用的魅蓝Note测试，发现弹出是否开启摄像头，我点击拒绝，会炸掉

**Comment by bertsir** [comment]
@Xu-YongFeng  是的，拒绝权限屏幕可能会是黑的，建议在外部启动之前检查一下权限，内部权限处理近期有时间了会加
