### ISSUE TITLE
部分机型会报java.lang.RuntimeException: autoFocus  这样的错误。

### ISSUE THREAD

**Issue by x930073498** [bertsir/zBarLibary#16]
以上的错误可能出现在部分华为手机上，
报错位置为：大概原因可能是camera的startPreview是异步的，快速调用autofocus可能会报错。
 private void startCameraPreview(SurfaceHolder holder) {
        try {
            mCameraManager.startPreview(holder, mPreviewCallback);
            mCameraManager.autoFocus(mFocusCallback);

        } catch (Exception e) {
            e.printStackTrace();

        }
    }

**Comment by bertsir** [comment]
@x930073498 会造成崩溃么

**Comment by x930073498** [comment]
@bertsir 不会，只是无法scan。
