### ISSUE TITLE
横屏模式下操作是反的。

### ISSUE THREAD

**Issue by wmailn** [bertsir/zBarLibary#19]
横屏模式下操作是反的，预览也是反的。

**Comment by bertsir** [comment]
@ZhanRu 有横屏需求？

**Comment by wmailn** [comment]
@bertsir 是的，公司项目强制横屏，测了下，横屏几乎无法使用。

**Comment by bertsir** [comment]
@ZhanRu 下载源码修改一下摄像头预览方向

**Comment by wmailn** [comment]
@bertsir 看了半天没找到，就换库了 (lll￢ω￢)

**Comment by bertsir** [comment]
@ZhanRu 好的  感谢反馈
