### ISSUE TITLE
我看代码里有设置声音，但是不出声音 请问怎么设置呢

### ISSUE THREAD

**Issue by Demonhuang** [bertsir/zBarLibary#2]
如题

**Comment by bertsir** [comment]
setPlaySound(true)

**Comment by Demonhuang** [comment]
<img width="1333" alt="wx20180104-173415 2x" src="https://user-images.githubusercontent.com/11385157/34557561-9cf35e7a-f175-11e7-872a-bfb85a32a854.png">
<img width="1385" alt="wx20180104-173430 2x" src="https://user-images.githubusercontent.com/11385157/34557562-9ebf90c0-f175-11e7-8bce-79a5594c1870.png">
一直再报这个错误 不知道为什么 请问什么原因呢？

**Comment by Demonhuang** [comment]
我是把你的代码都弄到我的项目里了 然后一直这个错误。。

**Comment by Demonhuang** [comment]
项目很紧 希望能帮我解决这个问题十分感谢

**Comment by Demonhuang** [comment]
<img width="1359" alt="wx20180104-180819 2x" src="https://user-images.githubusercontent.com/11385157/34558749-476d1478-f17a-11e7-997f-89a70e4b9a9f.png">
打了Log在这里有问题

**Comment by bertsir** [comment]
可能包名问题 给个QQ  我加你

**Comment by Demonhuang** [comment]
515386338 多谢 我挺着急的
