### ISSUE TITLE
为什么我一使用就报错了呢？

### ISSUE THREAD

**Issue by pangtianwang** [bertsir/zBarLibary#22]
java.lang.NoSuchFieldError: no "Ljava/lang/Object;" field "data" in class "Lcn/bertsir/zbar/Qr/Image;" or its superclasses

**Comment by bertsir** [comment]
@ pangtianwang  什么机型呢

**Comment by pangtianwang** [comment]
很神奇，昨天我一点开使用就闪退了，用的是魅族魅蓝M5s，但是今天我打开之后就没问题了，是不是与我卸载NDK有关系呢？非常感谢大神的回复，谢谢！能否加个微信呢？（18826237484）
