### ISSUE TITLE
你好，有个问题。

### ISSUE THREAD

**Issue by sj8521123** [bertsir/zBarLibary#26]
项目中集成了zBarLibary库，一直都能正常运行，今天11号，运行提示找不到类QRUtils 位置程序包cn.bertsir.zbar，不知道是否是你昨天更新产生问题？谢谢

**Comment by bertsir** [comment]
@sj8521123 嗯 昨天升级吧那个类换了个位置，rebuild就OK了  或者把版本号指定到1.1.5以下

**Comment by sj8521123** [comment]
可以了，rebuild了一下。

**Comment by sj8521123** [comment]
感谢。
