### ISSUE TITLE
如何调整扫描框的位置

### ISSUE THREAD

**Issue by ByteRax** [bertsir/zBarLibary#27]
尝试过向上偏移，也修改过您的算法，但是始终晕乎乎，改完之后，怎么调整都扫不出来

**Comment by bertsir** [comment]
@tanranran 还需要调整CameraScanAnalysis中101-110的代码

**Comment by ByteRax** [comment]
@bertsir  尝试调整过这里的。。。比例换算，怎么换都是有问题。。。晕乎乎

**Comment by bertsir** [comment]
@tanranran 预览的和底层处理的不是同一个方向  你在换算的时候注意调整90度试试
