### ISSUE TITLE
More than one file was found with OS independent path 'lib/mips/libiconv.so'

### ISSUE THREAD

**Issue by AndroidBody** [bertsir/zBarLibary#28]
More than one file was found with OS independent path 'lib/mips/libiconv.so'
这个有好的解决方案吗？谢谢

**Comment by bertsir** [comment]
@AndroidBody 你app的build,gradle应该配置有问题

**Comment by bertsir** [comment]
android {
    
    packagingOptions {
        pickFirst 'lib/armeabi-v7a/libiconv.so'
        pickFirst 'lib/armeabi-v8a/libiconv.so'
        pickFirst 'lib/arm64-v8a/libiconv.so'
        pickFirst 'lib/x86/libiconv.so'
        pickFirst 'lib/x86_64/libiconv.so'
    }
}
