### ISSUE TITLE
你好,用了你的扫描库,有几率无故出现条形码的结果

### ISSUE THREAD

**Issue by doitzhangwangcheng** [bertsir/zBarLibary#3]
不知道,该怎么描述这个现象,^_^ 即使我没有扫描任何带有二维码或者条形码的物品,也会在一分钟左右弹出一个条形码的吐司

**Comment by bertsir** [comment]
嗯 这个是已知问题，由于zbar的过于敏感导致（图像中略微出现类似于条形码或者二维码的时候），正在寻找解决方案

**Comment by bertsir** [comment]
@BestDraven 问题已经修复，更新一下就可以了
