### ISSUE TITLE
发现一个问题，扫描的时候离二维码近的充满整个框的时候，就扫描不出来，然后拉的远点扫描就很快

### ISSUE THREAD

**Issue by yan885283** [bertsir/zBarLibary#33]
发现一个问题，扫描的时候离二维码近的充满整个框的时候，就扫描不出来，然后拉的远点扫描就很快，demo也是这样的

**Comment by bertsir** [comment]
@yan885283 特别近的时候摄像头应该就不对焦了吧  不对焦没回调

**Comment by moselon** [comment]
我也发现一个问题，开始扫描没有对准二维码，在移到扫描框里扫描，二维码就变超大，超出了整个扫描框，要拉很远才会能扫描到二维码
