### ISSUE TITLE
请问，我正常debug运行的时候是没有问题，打包之后就会报错崩溃，是因为混淆的缘故吗？

### ISSUE THREAD

**Issue by yan885283** [bertsir/zBarLibary#34]
![image](https://user-images.githubusercontent.com/25768605/48338919-e02d7a00-e6a1-11e8-856e-d090759de2e4.png)
这个确认了是混淆的原因，我把混淆关掉就好了，请问这个引入的话混淆文件能发一份吗？

**Comment by bertsir** [comment]
@yan885283  不用混淆二维码库 -keep class cn.bertsir.zbar { *; }

**Comment by yan885283** [comment]
> @ yan885283 不用混淆二维码库-keep class cn.bertsir.zbar {*; }

不行的，我下载你的代码混淆之后都不行，一样的错误，麻烦帮我看下，项目要上线了，很着急

**Comment by yan885283** [comment]
可以了，加上这行混淆代码就行了-keep class cn.bertsir.zbar.Qr.** { *; }
