### ISSUE TITLE
对于部分没有闪光灯的机器，setFlash();会闪退，报空指针异常

### ISSUE THREAD

**Issue by DwayneZhang** [bertsir/zBarLibary#35]
为了适配没有闪光灯的机器，建议作者加上parameters.getFlashMode() 非空判断

` 
public void setFlash(){
        if(mCamera != null){
            Camera.Parameters parameters = mCamera.getParameters();
            if(parameters.getFlashMode() == null) return; //适配没有闪光灯的机器
            if(parameters.getFlashMode().endsWith(Camera.Parameters.FLASH_MODE_TORCH)){
                parameters.setFlashMode(Camera.Parameters.FLASH_MODE_OFF);
            }else {
                parameters.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
            }
            mCamera.setParameters(parameters);
        }
    }
`

`
public void setFlash(boolean open){
        if(mCamera != null){
            Camera.Parameters parameters = mCamera.getParameters();
            if(parameters.getFlashMode() == null) return; //适配没有闪光灯的机器
            if(!open){
                if(parameters.getFlashMode().endsWith(Camera.Parameters.FLASH_MODE_TORCH)){
                    parameters.setFlashMode(Camera.Parameters.FLASH_MODE_OFF);
                }
            }else {
                if(parameters.getFlashMode().endsWith(Camera.Parameters.FLASH_MODE_OFF)){
                    parameters.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
                }
            }
            mCamera.setParameters(parameters);
        }
    }
`

**Comment by bertsir** [comment]
@DwayneZhang 已修复，感谢支持
