### ISSUE TITLE
请问如何修改qrActivity实现连续扫描

### ISSUE THREAD

**Issue by wekingtan1991** [bertsir/zBarLibary#37]
我尝试过修改 QrActivity 实现连续扫码，但一直不成功。请问作者可以指导比较详细的思路吗？谢谢

**Comment by bertsir** [comment]
@wekingtan1991 注意 CameraScanAnalysis 的130和131行

**Comment by wekingtan1991** [comment]
> @wekingtan1991 注意 CameraScanAnalysis 的130和131行

修改好了，非常感谢！！！！
