### ISSUE TITLE
不能扫描条形码

### ISSUE THREAD

**Issue by lxhtiamo** [bertsir/zBarLibary#4]
希望加入扫描条形码

**Comment by bertsir** [comment]
@lxhtiamo 你好，支持扫描条形码的  .setScanType(QrConfig.TYPE_QRCODE)//设置扫描框类型（二维码，条形码）

**Comment by lxhtiamo** [comment]
能不能弄一个二合一的功能 在配置里面设置 .就是能同时扫描二维码和条形码??

**Comment by bertsir** [comment]
@lxhtiamo 历史版本是那样的，现在的识别条形码也支持识别二维码，但是识别二维码就是单纯的识别二维码，不过谢谢你的建议，下个版本会预留你要的功能

**Comment by lxhtiamo** [comment]
@bertsir 识别率真不错,比微信的还要快,识别条码的确也能扫描二维码,    就是码不在扫码框里面也能扫的出来..........................................只要是视图出现码就能识别...

**Comment by bertsir** [comment]
@lxhtiamo 下个版本会用大框来兼容两种码的扫描

**Comment by bertsir** [comment]
@lxhtiamo 新版本已支持你的需求，感谢支持
