### ISSUE TITLE
如果我是一张网络图片 已经获取Uri和bitmap 不想下载 如何直接识别二维码 ？

### ISSUE THREAD

**Issue by clearhui** [bertsir/zBarLibary#44]
目前只支持识别本地图片和bitmap 但是有一些bitmap识别不了

**Comment by clearhui** [comment]
举个例子 有个群聊信息 群内成员聊天 发送一张带有二维码的图片 
其他用户可以长按识别图中二维码 图片用imageloader 已经加载完毕 也可以获得Uri和bitmap 但是识别不出来

**Comment by bertsir** [comment]
@cjhfmm 建议先使用zbar的本地识别(decodeQRcode)不行的话使用zxing的本地识别再试一次（decodeQRcodeByZxing），都空的时候建议跳转图片裁剪，让用户手动裁剪一下图片

**Comment by clearhui** [comment]
使用zxing的本地识别再试一次（decodeQRcodeByZxing）这种方案不可行 因为没有本地路径

**Comment by bertsir** [comment]
@cjhfmm down源码稍作修改，虽然传入的是路径，最终都转换成了Bitmap

**Comment by clearhui** [comment]
好的 多谢
