### ISSUE TITLE
Fragment中如何调用？

### ISSUE THREAD

**Issue by kayroc** [bertsir/zBarLibary#45]
Fragment中扫描没反应，请问应该怎么用？

**Comment by bertsir** [comment]
QrManager.getInstance().init(qrConfig).startScan(getActivity(), new QrManager.OnScanResultCallback() {}

**Comment by bertsir** [comment]
@Kayroc   QrManager.getInstance().init(qrConfig).startScan(getActivity(), new QrManager.OnScanResultCallback() {

**Comment by kayroc** [comment]
@bertsir 奇怪，我也是这样啊！用的是1.2.1，activity中也没反应啦。

**Comment by bertsir** [comment]
粘贴一下完整代码

**Comment by bertsir** [comment]
@Kayroc 粘贴一下完整代码

**Comment by kayroc** [comment]
@bertsir 已解决，粘贴的之前的代码限制了扫码类型！
