### ISSUE TITLE
华为手机报错

### ISSUE THREAD

**Issue by ny1992** [bertsir/zBarLibary#46]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.astrongtech.togroup/cn.bertsir.zbar.QRActivity}: java.lang.ClassCastException: android.graphics.drawable.StateListDrawable cannot be cast to android.graphics.drawable.LayerDrawable

**Comment by bertsir** [comment]
@ny1992 华为什么机型 Android 版本多少

**Comment by ny1992** [comment]
p8 lite 系统5.0.1

**Comment by bertsir** [comment]
@ny1992 刚才更新了  应该解决了

**Comment by ny1992** [comment]
demo报错啊

**Comment by bertsir** [comment]
@ny1992 刚在优测试了P8 LITE  没问题，你把旧的DEMO卸载掉，重新下载试试

**Comment by ny1992** [comment]
我运行了demo，扫描动画会卡顿

**Comment by bertsir** [comment]
@ny1992 尝试关闭一下自动拉近试试

**Comment by ny1992** [comment]
解决了，非常感谢🙏

**Comment by bertsir** [comment]
@ny1992 已经优化了扫描动画卡顿的问题，你可以更新试试

**Comment by ny1992** [comment]
1.2.5这个版本吗

**Comment by bertsir** [comment]
@ny1992 是的
