### ISSUE TITLE
manifest合并优先级的问题

### ISSUE THREAD

**Issue by HolyAnnLee** [bertsir/zBarLibary#47]
求助，引入包的manifest合并优先级为什么比我本地的高啊
![QQ截图20190313171016](https://user-images.githubusercontent.com/32293217/54266716-e6315a00-45b2-11e9-9cb1-18cf9a9f6dae.png)

**Comment by bertsir** [comment]
@HolyAnnLee 不太明白你的意思

**Comment by HolyAnnLee** [comment]
引入包里的provider覆盖了项目里的provider。。。

**Comment by HolyAnnLee** [comment]
我两个app都引用这个包，但只能安装一个，第二个安装的时候一直提示与已安装应用内容提供者冲突
![QQ截图20190313171923](https://user-images.githubusercontent.com/32293217/54267574-6e642f00-45b4-11e9-95c2-93ffe3d74e70.png)

**Comment by HolyAnnLee** [comment]
应该是provider中authorities被覆盖的原因

**Comment by bertsir** [comment]
@HolyAnnLee 嗯 因为我把authorities写死了,多个项目的话可能会提示冲突

**Comment by HolyAnnLee** [comment]
请问有什么方法可以让我本地项目中的authorities不被包中的authorities覆盖掉吗

**Comment by bertsir** [comment]
@HolyAnnLee 我修改一下authorities，稍等

**Comment by HolyAnnLee** [comment]
嗯嗯

**Comment by bertsir** [comment]
@HolyAnnLee OK了

**Comment by HolyAnnLee** [comment]
@bertsir 可以啦，多谢大佬
