### ISSUE TITLE
横屏时扫描页面被旋转了，如何解决？

### ISSUE THREAD

**Issue by kayroc** [bertsir/zBarLibary#50]
![被旋转效果图](https://i.imgur.com/5sseO5P.png)

**Comment by bertsir** [comment]
@Kayroc 建议强制指向竖屏

**Comment by kayroc** [comment]
@bertsir 但是我们这个是平板项目，必须横屏，怎么办呀？

**Comment by bertsir** [comment]
@Kayroc 私我QQ我给你个包试试 18100950
