### ISSUE TITLE
扫描界面的返回键

### ISSUE THREAD

**Issue by msdogo** [bertsir/zBarLibary#51]
首先感谢楼主的封装库，识别很快。请问能否将扫描界面的返回键按钮图片设置暴露个接口出来吗？

**Comment by bertsir** [comment]
@devlwj 这么细致的需求，建议还是引入module修改吧,毕竟提供了修改图片接口，接下来就又要设置图片大小的

**Comment by msdogo** [comment]
哈哈，确实！为了保证UI效果统一，目前是引入module来自己改的，感谢神速回复！
