### ISSUE TITLE
请问默认是全屏扫码 可以定义只框内扫码吗

### ISSUE THREAD

**Issue by dssyang** [bertsir/zBarLibary#66]
请问最新版本可以定义 范围内的框内扫码吗？非常感谢！

**Comment by bertsir** [comment]
@dssyang 如果不开启双引擎模式的话是可以选择只识别框内的

**Comment by dssyang** [comment]
@bertsir 谢谢回答。您说的双引擎模式是在调用的代码里，可以直接设置，是吗？
麻烦您，能给一下该属性的名称吗？

**Comment by bertsir** [comment]
@dssyang setDoubleEngine 默认是false

**Comment by dssyang** [comment]
@bertsir 扫一本的条形码时，这个也起作用吗？看好像是对于QR CODE的。
现在扫条形码时，框外的码也 被扫到了。

**Comment by dssyang** [comment]
@bertsir 用提供的DEMO试了一下，发现选是否启用双擎好像没影响，如果选择了只扫描框内内容 就可以了。
这个选项默认是不是不开呢。
1.1.7版是否也有呢？
谢谢。
