### ISSUE TITLE
可否在回调中增加识别的是二维码还是条形码？

### ISSUE THREAD

**Issue by samgsmg** [bertsir/zBarLibary#69]
比如这样：
@Override
            public void onScanSuccess(int  Type, String result) {
               i
                Toast.makeText(getApplicationContext(), result, Toast.LENGTH_SHORT).show();
            }

方便程序可以跟据是二维码还是条形码做不同的操作

**Comment by bertsir** [comment]
@samgsmg 可以，近期添加

**Comment by bertsir** [comment]
@samgsmg 很好的建议，已经添加了
