### ISSUE TITLE
库很眼熟，并且有同样的bug

### ISSUE THREAD

**Issue by Reginer** [bertsir/zBarLibary#7]
扫这个二维码试试，结果是你好两个字。扫出来乱码。
![image](https://user-images.githubusercontent.com/12568257/35963006-521d6668-0cee-11e8-9383-0254b6af1a95.png)

**Comment by bertsir** [comment]
@Reginer 确实有这问题，试了别的中文好像没问题，“好你”也不行，我找找解决方案

**Comment by bertsir** [comment]
@Reginer 你说的问题，已经修复了，你可以先下载Demo体验一下，我同时试了简体和繁体，中文日文，韩文，俄语的你好都正常，感谢支持

**Comment by Reginer** [comment]
有提供demo么？找了下没发现下载地址。代码也没看到更新，我自己编译也可以的

**Comment by bertsir** [comment]
@Reginer https://www.pgyer.com/CyKm  你可以先试试，看看还有什么BUG

**Comment by bertsir** [comment]
@Reginer 等你确认了你的问题解决后，我在同时提交jcenter和github

**Comment by Reginer** [comment]
没发现什么问题，感觉挺牛逼的

**Comment by bertsir** [comment]
@Reginer 代码提交了，jcenter稍后生效，感谢支持
