### ISSUE TITLE
Samsung SM-N7506V 调用生成二维码和扫描都报错

### ISSUE THREAD

**Issue by zdmisif** [bertsir/zBarLibary#80]
09-17 16:14:45.924 377-377/ E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.google.zxing.MultiFormatWriter
        at cn.bertsir.zbar.utils.QRUtils.createQRCode(QRUtils.java:263)
        at cn.bertsir.zbar.utils.QRUtils.createQRCode(QRUtils.java:251)

**Comment by zdmisif** [comment]
1.3.6版本会报错，1.3.5版则不会

**Comment by bertsir** [comment]
@zdmisif 收到 现在检查原因修复

**Comment by bertsir** [comment]
@zdmisif 本地直接依赖project没问题，可能是因为昨天网络波动导致生成库的时候丢失了依赖，这会想重新提交一下，无奈又被挡住了，先用1.3.5吧，可以提交了我会更新

**Comment by bertsir** [comment]
@zdmisif 应该ok了，版本还是1.3.6

**Comment by zdmisif** [comment]
![image](https://user-images.githubusercontent.com/8085248/65034605-f4a16980-d979-11e9-8f93-026d6a24b459.png)
![image](https://user-images.githubusercontent.com/8085248/65034626-ff5bfe80-d979-11e9-87f6-84588f6c75ab.png)
刚试了1.3.6版还是有问题~

**Comment by bertsir** [comment]
@zdmisif clean或者rebuild试试呢  新版的AS好像会将库缓存到本地

**Comment by bertsir** [comment]
@zdmisif /.gradle/caches/modules-2/files-2.1   找到这下面  把缓存都删掉

**Comment by zdmisif** [comment]
还是一样，清了缓存也是不行，有可能是对应机型问题？

**Comment by bertsir** [comment]
@zdmisif 应该不是，尝试一下别的机型试试呢

**Comment by lucifinilsu** [comment]
解决没有？

**Comment by zdmisif** [comment]
1.3.5不加依赖 implementation 'com.google.zxing:core:3.3.0'运行不会报错，但是1.3.6不加则会报错

**Comment by zdmisif** [comment]
加上了就暂时没发现问题

**Comment by bertsir** [comment]
@zdmisif 是的，因为没修复 版的1.3.6确实是因为误改了依赖方式导致的
