### ISSUE TITLE
这个二维码 扫起来很慢

### ISSUE THREAD

**Issue by 912334508** [bertsir/zBarLibary#82]
老哥 救救我！！https://pan.baidu.com/s/1YaZn7xR2SRQwGdotQHHdtQ

**Comment by bertsir** [comment]
@912334508 双识别引擎打开试试

**Comment by 912334508** [comment]
开了  可以扫 很慢！！！ 老哥 有啥解决办法不！！！




------------------ 原始邮件 ------------------
发件人: "bertsir"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 下午2:32
收件人: "bertsir/zBarLibary"<zBarLibary@noreply.github.com>; 
抄送: "↘僦伱⒈個ゞ &#9829;"<912334508@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [bertsir/zBarLibary] 这个二维码 扫起来很慢 (#82)




@912334508 双识别引擎打开试试

**Comment by bertsir** [comment]
暂时没有


发自Bert


在2019年09月18日 14:34，912334508<notifications@github.com> 写道：
开了 可以扫 很慢！！！ 老哥 有啥解决办法不！！！




------------------ 原始邮件 ------------------
发件人: "bertsir"<notifications@github.com>;
发送时间: 2019年9月18日(星期三) 下午2:32
收件人: "bertsir/zBarLibary"<zBarLibary@noreply.github.com>;
抄送: "↘僦伱⒈個ゞ &#9829;"<912334508@qq.com>; "Mention"<mention@noreply.github.com>;
主题: Re: [bertsir/zBarLibary] 这个二维码 扫起来很慢 (#82)




@912334508 双识别引擎打开试试

**Comment by lucifinilsu** [comment]
你这个码，我开了双引擎简直秒扫啊。。。换手机试试吧

**Comment by 912334508** [comment]
好的！！！




------------------ 原始邮件 ------------------
发件人: "lucifinilsu"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 下午2:49
收件人: "bertsir/zBarLibary"<zBarLibary@noreply.github.com>; 
抄送: "↘僦伱⒈個ゞ &#9829;"<912334508@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [bertsir/zBarLibary] 这个二维码 扫起来很慢 (#82)




你这个码，我开了双引擎简直秒扫啊。。。换手机试试吧

**Comment by 912334508** [comment]
那个...只扫描框中内容勾选了  也是全屏扫描！




------------------ 原始邮件 ------------------
发件人: "bertsir"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 下午2:45
收件人: "bertsir/zBarLibary"<zBarLibary@noreply.github.com>; 
抄送: "↘僦伱⒈個ゞ &#9829;"<912334508@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [bertsir/zBarLibary] 这个二维码 扫起来很慢 (#82)



暂时没有
 
 
 发自Bert
 
 
 在2019年09月18日 14:34，912334508<notifications@github.com> 写道：
 开了 可以扫 很慢！！！ 老哥 有啥解决办法不！！！
 
 
 
 
 ------------------ 原始邮件 ------------------
 发件人: "bertsir"<notifications@github.com>;
 发送时间: 2019年9月18日(星期三) 下午2:32
 收件人: "bertsir/zBarLibary"<zBarLibary@noreply.github.com>;
 抄送: "↘僦伱⒈個ゞ &#9829;"<912334508@qq.com>; "Mention"<mention@noreply.github.com>;
 主题: Re: [bertsir/zBarLibary] 这个二维码 扫起来很慢 (#82)
 
 
 
 
 @912334508 双识别引擎打开试试

**Comment by bertsir** [comment]
@912334508 开启双引擎，只识别框中会失效，文档有说

**Comment by 912334508** [comment]
OK  谢谢！！




------------------ 原始邮件 ------------------
发件人: "bertsir"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 下午3:08
收件人: "bertsir/zBarLibary"<zBarLibary@noreply.github.com>; 
抄送: "↘僦伱⒈個ゞ &#9829;"<912334508@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [bertsir/zBarLibary] 这个二维码 扫起来很慢 (#82)




@912334508 开启双引擎，只识别框中会失效，文档有说
