### ISSUE TITLE
对一些本地相册的彩色二位码图片的解析好像有问题，比如这个

### ISSUE THREAD

**Issue by lucifinilsu** [bertsir/zBarLibary#84]
从相册里选取这个图片识别不了，但是直接用摄像头直接对着扫秒开
![无法识别](https://mstatic.gzstv.com/media/images/2019/09/02/dHS1fsOJDcUt.png)

**Comment by bertsir** [comment]
@lucifinilsu 这个会随着下午的版本一起支持，貌似发现一个2K的库也不支持，哈哈哈

**Comment by lucifinilsu** [comment]
> @lucifinilsu 这个会随着下午的版本一起支持，貌似发现一个2K的库也不支持，哈哈哈

嘿嘿，加油，坐等你更新！

**Comment by lucifinilsu** [comment]
> @lucifinilsu 这个会随着下午的版本一起支持，貌似发现一个2K的库也不支持，哈哈哈

嘿嘿，加油，坐等你更新！
