### ISSUE TITLE
扫码识别不出来

### ISSUE THREAD

**Issue by HoneyWorld** [bertsir/zBarLibary#91]
![70ETCO{RJ9$(5Q30DHFKJX1](https://user-images.githubusercontent.com/13584168/67560247-10541880-f74d-11e9-890d-86af1f1d1fc3.png)
![W1L V2_`%VQSG9~MP`WBVLF](https://user-images.githubusercontent.com/13584168/67560249-10ecaf00-f74d-11e9-86e8-89fff33133f6.png)
![D}L`S@ ZI)B A@T8A~XNMQH](https://user-images.githubusercontent.com/13584168/67560251-10ecaf00-f74d-11e9-999f-83c935a3822d.png)
![S3P0{@(O$HUU8)P@M TD8QK](https://user-images.githubusercontent.com/13584168/67560252-11854580-f74d-11e9-8107-40ed736f374f.png)

**Comment by bertsir** [comment]
@HoneyWorld 刚试了没问题，识别慢的话就开双识别，其次，不要把二维码倒着放，倒放啥都扫不出来

**Comment by HoneyWorld** [comment]
@bertsir 我又去现场测试了一下，二维码稍微模糊一点，对识别效率影响很大，苹果这方面要比安卓好很多，现场测试一片尴尬

**Comment by HoneyWorld** [comment]
实际二维码大一些，清晰一些，识别效率很高的，在公司测试生成的二维码扫码非常快，但是在现场就不行了，对比太明显

**Comment by HoneyWorld** [comment]
正常扫描
![` {1M2XC7{22C}MZVB6Q(AW](https://user-images.githubusercontent.com/13584168/67612889-c5341700-f7d9-11e9-8fec-ea60557b592c.png)

**Comment by HoneyWorld** [comment]
现场扫码
![IMG_20191026_082702](https://user-images.githubusercontent.com/13584168/67612901-ee54a780-f7d9-11e9-9654-26a651f6610e.jpg)
![IMG_20191026_082707_1](https://user-images.githubusercontent.com/13584168/67612902-ee54a780-f7d9-11e9-90e2-862bd7ff5c6d.jpg)
![Uploading IMG_20191026_082716.jpg…]()
![Uploading IMG_20191026_082655.jpg…]()

**Comment by sys-banana** [comment]
z这种的扫不出来

**Comment by sys-banana** [comment]
![Uploading Snipaste_2020-12-09_09-49-02.jpg…]()
