### ISSUE TITLE
6.0手机ZTEBV0730开启双引擎扫描二维码会崩溃

### ISSUE THREAD

**Issue by githubZYQ** [bertsir/zBarLibary#99]
如题：使用6.0手机ZTEBV0730开启双引擎扫描二维码会崩溃。
详细解释：如不开启双引擎或者扫描的是条码则不会崩溃。
跟踪：问题来源是zxing3.4.0不支持7.0以下手机
这篇文章有解释：https://www.jianshu.com/p/1517a7e44f3e
这个问题在zxing的源码处也有issues
原文地址：https://github.com/zxing/zxing/issues/1170
作者的建议是降低zxing版本到3.3.x；
SO：
建议作者降低zxing版本
或者开启双引擎时判断当前手机系统，如果7.0以下手机禁止开启zxing去识别二维码。

**Comment by bertsir** [comment]
@githubZYQ 好的，我降低版本
